import Footer from '@components/Footer';
import Header from '@components/Header';
import { Open_Sans } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import '../globals.css';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
	title: 'Discord Clone',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={openSans.className}>{children}</body>
			</html>
		</ClerkProvider>
	);
}
