import Footer from '@components/Footer';
import Header from '@components/Header';
import { Open_Sans } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import '../globals.css';
import { ThemeProvider } from '@components/providers/theme-provider';
import { cn } from '@lib/utils';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
	title: 'Discord Clone',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html
				lang='en'
				suppressHydrationWarning
			>
				<body className={cn(openSans.className, 'bg-white dark:bg-[#313338]')}>
					<ThemeProvider
						attribute='class'
						defaultTheme='dark'
						enableSystem
						storageKey='discord-theme'
					>
						{children}
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
